name: Doxygen Action

on: [push]
#on: 
#  push:
#    branches:
#      - doxygen-updates
#  workflow_run:
#    workflows: ["Release"]
#    types: [completed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses : action/checkout@v2
        - name : actions for protobuff
          uses : pseudomuto/protoc-gen-doc
          with:
            doc_out : ./docs/html
            doc_opt : html,index.html proto/*.proto