name: Doxygen Action
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses : actions/checkout@v2
        - name : actions for protobuff
          uses : pseudomuto/protoc-gen-doc
          with:
            doc_out : ./docs/html
            doc_opt : html,index.html proto/*.proto