name: Doxygen Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
          token: ${{ secrets.SUBMODULE_PAT || github.token}}
      - name: Install Doxygen
        run: sudo apt-get install doxygen -y
        shell: bash
      - name: Doxygen for Protobuf Action
        run : doxygen Doxyfile 
        shell: bash
      - name: PowerShell@2
        run:
            script: |
             $xml = [Xml] (Get-Content .\MyApp\MyApp.csproj)
             $version = $xml.Project.PropertyGroup.Version
             echo $version
             echo "##vso[task.setvariable variable=version]$version"
      - name: GH Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: gh-pages-test
